# Generated by Django 2.2 on 2019-04-19 18:20

import appQRMusical.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('appQRMusical', '0001_initial'), ('appQRMusical', '0002_auto_20180902_0254'), ('appQRMusical', '0003_auto_20180902_0346'), ('appQRMusical', '0004_auto_20180902_0400'), ('appQRMusical', '0005_auto_20180902_2356'), ('appQRMusical', '0006_auto_20180903_0055'), ('appQRMusical', '0007_actividad_juego'), ('appQRMusical', '0008_auto_20190324_1546'), ('appQRMusical', '0009_auto_20190324_1547'), ('appQRMusical', '0010_remove_actividad_juego'), ('appQRMusical', '0011_actividad_juego'), ('appQRMusical', '0012_auto_20190324_1555'), ('appQRMusical', '0013_auto_20190324_1558'), ('appQRMusical', '0014_delete_terapia_indicador'), ('appQRMusical', '0015_qui'), ('appQRMusical', '0016_qui_relacionado'), ('appQRMusical', '0017_qui_indicador'), ('appQRMusical', '0018_auto_20190413_2132'), ('appQRMusical', '0019_auto_20190413_2133'), ('appQRMusical', '0020_auto_20190413_2134'), ('appQRMusical', '0021_auto_20190413_2136'), ('appQRMusical', '0022_quises'), ('appQRMusical', '0023_auto_20190414_1942'), ('appQRMusical', '0024_delete_texto'), ('appQRMusical', '0025_auto_20190415_1718'), ('appQRMusical', '0026_auto_20190415_1730'), ('appQRMusical', '0027_actividad_pregunta_pregunta_pregunta_matching_pregunta_quizz'), ('appQRMusical', '0028_auto_20190416_1343'), ('appQRMusical', '0029_auto_20190419_1831'), ('appQRMusical', '0030_multimedia_video'), ('appQRMusical', '0031_auto_20190419_2007'), ('appQRMusical', '0032_auto_20190419_2010'), ('appQRMusical', '0033_auto_20190419_2012'), ('appQRMusical', '0034_auto_20190419_2015')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('desripcion', models.CharField(blank=True, max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asigna_Terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Asigna_Terapia')),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('contenido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Contenido')),
                ('nombre', models.CharField(max_length=100)),
                ('audio', models.FileField(blank=True, null=True, upload_to=appQRMusical.models.generarDirectorioSubida)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('filetype', models.CharField(max_length=3)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=appQRMusical.models.generarDirectorioSubida)),
            ],
            options={
                'ordering': ('datetime',),
            },
            bases=('appQRMusical.contenido',),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('valoracion', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Terapia_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Terapia')),
            ],
            options={
                'unique_together': {('actividad', 'terapia')},
            },
        ),
        migrations.CreateModel(
            name='Supervisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Especialista')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Tratamiento')),
            ],
            options={
                'unique_together': {('especialista', 'tratamiento')},
            },
        ),
        migrations.CreateModel(
            name='Resultado_Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Indicador', to_field='id')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Sesion')),
            ],
            options={
                'unique_together': {('sesion', 'indicador', 'actividad')},
            },
        ),
        migrations.CreateModel(
            name='Especialista_Asigna_Terapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('asigna_terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Asigna_Terapia')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Especialista')),
            ],
            options={
                'unique_together': {('asigna_terapia', 'especialista', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Categoria_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Categoria')),
            ],
            options={
                'unique_together': {('categoria', 'actividad')},
            },
        ),
        migrations.CreateModel(
            name='Actividad_Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Contenido')),
            ],
            options={
                'unique_together': {('actividad', 'contenido')},
            },
        ),
        migrations.CreateModel(
            name='Asigna_Terapia',
            fields=[
                ('id_asign_therapy', models.AutoField(primary_key=True, serialize=False)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Tratamiento')),
                ('terapia', models.ManyToManyField(to='appQRMusical.Terapia')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, upload_to='profiles/')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('nivel', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1)),
                ('codigo', models.CharField(blank=True, max_length=8)),
                ('online', models.CharField(choices=[('si', 'si'), ('no', 'no')], default='no', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activado', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('proposito', models.CharField(blank=True, max_length=100)),
                ('indicador', models.ManyToManyField(blank=True, to='appQRMusical.Indicador')),
                ('juego', models.CharField(choices=[('Matching', 'Matching'), ('Quizz', 'Quizz'), ('Calculo', 'Calculo')], default='Matching', max_length=20)),
                ('aleatorio', models.BooleanField(default=False)),
                ('narracion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta_Matching',
            fields=[
                ('pregunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Pregunta')),
                ('multimediaCorrecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimediaCorrecto+', to='appQRMusical.Multimedia')),
            ],
            bases=('appQRMusical.pregunta',),
        ),
        migrations.CreateModel(
            name='Actividad_Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Pregunta')),
            ],
            options={
                'unique_together': {('actividad', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('formato', models.CharField(choices=[('Texto', 'Texto'), ('Imagen', 'Imagen'), ('Audio', 'Audio'), ('Video', 'Video')], default='Imagen', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta_Quizz',
            fields=[
                ('pregunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Pregunta')),
                ('visualizacion', models.CharField(choices=[('Multiopcion', 'Multiopcion'), ('Unica', 'Unica')], default='Unica', max_length=20)),
                ('multimediaCorrecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimediaCorrecto+', to='appQRMusical.Multimedia')),
                ('multimediaIncorrecto', models.ManyToManyField(related_name='_pregunta_quizz_multimediaIncorrecto_+', to='appQRMusical.Multimedia')),
            ],
            bases=('appQRMusical.pregunta',),
        ),
    ]
