# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-13 22:14
from __future__ import unicode_literals

import appQRMusical.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('proposito', models.CharField(blank=True, max_length=100)),
                ('juego', models.CharField(choices=[('Matching', 'Matching'), ('Quizz', 'Quizz'), ('Calculo', 'Calculo')], default='Matching', max_length=20)),
                ('aleatorio', models.BooleanField(default=False)),
                ('narracion', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Actividad',
            },
        ),
        migrations.CreateModel(
            name='Actividad_Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
            ],
            options={
                'verbose_name_plural': 'Actividad_Contenido',
            },
        ),
        migrations.CreateModel(
            name='Actividad_Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
            ],
            options={
                'verbose_name_plural': 'Actividad_Pregunta',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Categoria_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categoria_Actividad',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Contenido',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valoracion', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Especialista',
            },
        ),
        migrations.CreateModel(
            name='Especialista_Terapia_Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Especialista')),
            ],
            options={
                'verbose_name_plural': 'Especialista_Terapia_Tratamiento',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Indicador',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, upload_to='profiles/')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('nivel', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1)),
                ('codigo', models.CharField(blank=True, max_length=8)),
                ('online', models.CharField(choices=[('si', 'si'), ('no', 'no')], default='no', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('formato', models.CharField(choices=[('Texto', 'Texto'), ('Imagen', 'Imagen'), ('Audio', 'Audio'), ('Video', 'Video')], default='Imagen', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Pregunta',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('', '')], default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Respuesta',
            },
        ),
        migrations.CreateModel(
            name='Resultado_Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Indicador')),
            ],
            options={
                'verbose_name_plural': 'Resultado_Sesion',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sesion',
            },
        ),
        migrations.CreateModel(
            name='Supervisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Especialista')),
            ],
            options={
                'verbose_name_plural': 'Supervisa',
            },
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Terapia',
            },
        ),
        migrations.CreateModel(
            name='Terapia_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Terapia')),
            ],
            options={
                'verbose_name_plural': 'Terapia_Actividad',
            },
        ),
        migrations.CreateModel(
            name='Terapia_Tratamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('terapia', models.ManyToManyField(to='appQRMusical.Terapia')),
            ],
            options={
                'verbose_name_plural': 'Terapia_Tratamiento',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activado', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Tratamiento',
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('contenido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Contenido')),
                ('nombre', models.CharField(max_length=100)),
                ('audio', models.FileField(blank=True, null=True, upload_to=appQRMusical.models.generarDirectorioSubida)),
                ('video', models.FileField(blank=True, null=True, upload_to=appQRMusical.models.generarDirectorioSubida)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('filetype', models.CharField(blank=True, max_length=3, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Multimedia',
                'ordering': ('datetime',),
            },
            bases=('appQRMusical.contenido',),
        ),
        migrations.CreateModel(
            name='Pregunta_Matching',
            fields=[
                ('pregunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Pregunta')),
                ('multimediaCorrecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimediaCorrecto+', to='appQRMusical.Multimedia')),
            ],
            options={
                'verbose_name_plural': 'Pregunta_Matching',
            },
            bases=('appQRMusical.pregunta',),
        ),
        migrations.CreateModel(
            name='Pregunta_Quizz',
            fields=[
                ('pregunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Pregunta')),
                ('visualizacion', models.CharField(choices=[('Multiopcion', 'Multiopcion'), ('Unica', 'Unica')], default='Unica', max_length=20)),
                ('multimediaCorrecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimediaCorrecto+', to='appQRMusical.Multimedia')),
                ('multimediaIncorrecto', models.ManyToManyField(related_name='_pregunta_quizz_multimediaIncorrecto_+', to='appQRMusical.Multimedia')),
            ],
            options={
                'verbose_name_plural': 'Pregunta_Quizz',
            },
            bases=('appQRMusical.pregunta',),
        ),
        migrations.AddField(
            model_name='terapia_tratamiento',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Tratamiento'),
        ),
        migrations.AddField(
            model_name='supervisa',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Tratamiento'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='terapia_tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Terapia_Tratamiento'),
        ),
        migrations.AddField(
            model_name='resultado_sesion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Sesion'),
        ),
        migrations.AddField(
            model_name='especialista_terapia_tratamiento',
            name='terapia_tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Terapia_Tratamiento'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Paciente'),
        ),
        migrations.AddField(
            model_name='actividad_pregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Pregunta'),
        ),
        migrations.AddField(
            model_name='actividad_contenido',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Contenido'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='indicador',
            field=models.ManyToManyField(blank=True, to='appQRMusical.Indicador'),
        ),
        migrations.AlterUniqueTogether(
            name='terapia_actividad',
            unique_together=set([('actividad', 'terapia')]),
        ),
        migrations.AlterUniqueTogether(
            name='supervisa',
            unique_together=set([('especialista', 'tratamiento')]),
        ),
        migrations.AlterUniqueTogether(
            name='resultado_sesion',
            unique_together=set([('sesion', 'indicador', 'actividad')]),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia+', to='appQRMusical.Multimedia'),
        ),
        migrations.AlterUniqueTogether(
            name='especialista_terapia_tratamiento',
            unique_together=set([('terapia_tratamiento', 'especialista', 'fecha')]),
        ),
        migrations.AlterUniqueTogether(
            name='categoria_actividad',
            unique_together=set([('categoria', 'actividad')]),
        ),
        migrations.AlterUniqueTogether(
            name='actividad_pregunta',
            unique_together=set([('actividad', 'pregunta')]),
        ),
        migrations.AlterUniqueTogether(
            name='actividad_contenido',
            unique_together=set([('actividad', 'contenido')]),
        ),
    ]
