# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-13 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='filetype',
        ),
        migrations.AlterField(
            model_name='actividad_pregunta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
