# Generated by Django 2.2 on 2019-04-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0001_squashed_0034_auto_20190419_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado_sesion',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Indicador'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Paciente'),
        ),
    ]
