# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-13 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0002_auto_20190514_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
