# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-14 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0003_auto_20190514_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta_matching',
            name='multimediaCorrecto',
        ),
        migrations.RemoveField(
            model_name='pregunta_quizz',
            name='multimediaCorrecto',
        ),
        migrations.RemoveField(
            model_name='pregunta_quizz',
            name='multimediaIncorrecto',
        ),
        migrations.AddField(
            model_name='pregunta_matching',
            name='multimediaPregunta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia+', to='appQRMusical.Multimedia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta_matching',
            name='respuesta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='respuesta+', to='appQRMusical.Respuesta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta_quizz',
            name='multimediaPregunta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pregunta+', to='appQRMusical.Multimedia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta_quizz',
            name='respuestas',
            field=models.ManyToManyField(related_name='_pregunta_quizz_respuestas_+', to='appQRMusical.Respuesta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='appQRMusical.Multimedia'),
        ),
    ]
