# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-20 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0004_auto_20190514_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('multimediaRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimediaRespuesta+', to='appQRMusical.Multimedia')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Pregunta')),
            ],
            options={
                'verbose_name_plural': 'Registro_Sesion',
            },
        ),
        migrations.AddField(
            model_name='sesion',
            name='actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro_sesion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesion+', to='appQRMusical.Sesion'),
        ),
    ]
