# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-20 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0005_auto_20190520_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_sesion',
            old_name='datetime',
            new_name='fecha',
        ),
    ]
