# Generated by Django 2.2 on 2019-03-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0006_auto_20180903_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='juego',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
