# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0007_auto_20190521_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='juego',
            field=models.CharField(choices=[('Matching', 'Matching'), ('Quizz', 'Quizz'), ('Evoca', 'Evoca')], default='Matching', max_length=20),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='resultado',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('', '')], default=None, max_length=20),
        ),
    ]
