# Generated by Django 2.2 on 2019-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0007_actividad_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='juego',
            field=models.TextField(choices=[('Matching', 'Matching'), ('Quizz', 'Quizz'), ('Calculo', 'Calculo')], default='Matching'),
        ),
    ]
