# Generated by Django 2.2 on 2019-03-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0009_auto_20190324_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='juego',
        ),
    ]
