# Generated by Django 2.2 on 2019-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0010_remove_actividad_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='juego',
            field=models.CharField(choices=[('Matching', 'Matching'), ('Quizz', 'Quizz'), ('Calculo', 'Calculo')], default='Matching', max_length=20),
        ),
    ]
