# Generated by Django 2.2 on 2019-03-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0013_auto_20190324_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Terapia_Indicador',
        ),
    ]
