# Generated by Django 2.2 on 2019-04-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0014_delete_terapia_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qui',
            fields=[
                ('contenido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Contenido')),
                ('data', models.CharField(blank=True, max_length=50)),
            ],
            bases=('appQRMusical.contenido',),
        ),
    ]
