# Generated by Django 2.2 on 2019-04-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0015_qui'),
    ]

    operations = [
        migrations.AddField(
            model_name='qui',
            name='relacionado',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='relacion+', to='appQRMusical.Contenido'),
            preserve_default=False,
        ),
    ]
