# Generated by Django 2.2 on 2019-04-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0016_qui_relacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='qui',
            name='indicador',
            field=models.ManyToManyField(blank=True, related_name='_qui_indicador_+', to='appQRMusical.Contenido'),
        ),
    ]
