# Generated by Django 2.2 on 2019-04-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0017_qui_indicador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qui',
            old_name='data',
            new_name='pregunta',
        ),
        migrations.RemoveField(
            model_name='qui',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='qui',
            name='relacionado',
        ),
        migrations.AddField(
            model_name='qui',
            name='falso',
            field=models.ManyToManyField(blank=True, related_name='_qui_falso_+', to='appQRMusical.Contenido'),
        ),
        migrations.AddField(
            model_name='qui',
            name='verdadero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verdadero+', to='appQRMusical.Contenido'),
            preserve_default=False,
        ),
    ]
