# Generated by Django 2.2 on 2019-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0018_auto_20190413_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qui',
            name='falso',
            field=models.ManyToManyField(related_name='_qui_falso_+', to='appQRMusical.Contenido'),
        ),
    ]
