# Generated by Django 2.2 on 2019-04-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0019_auto_20190413_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qui',
            name='pregunta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
