# Generated by Django 2.2 on 2019-04-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0020_auto_20190413_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qui',
            name='pregunta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
