# Generated by Django 2.2 on 2019-04-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0021_auto_20190413_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quises',
            fields=[
                ('contenido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Contenido')),
                ('pregunta', models.TextField(blank=True, null=True)),
                ('falso', models.ManyToManyField(related_name='_quises_falso_+', to='appQRMusical.Multimedia')),
                ('verdadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdadero1+', to='appQRMusical.Multimedia')),
            ],
            bases=('appQRMusical.contenido',),
        ),
    ]
