# Generated by Django 2.2 on 2019-04-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0022_quises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quises',
            name='contenido_ptr',
        ),
        migrations.RemoveField(
            model_name='quises',
            name='falso',
        ),
        migrations.RemoveField(
            model_name='quises',
            name='verdadero',
        ),
        migrations.DeleteModel(
            name='Qui',
        ),
        migrations.DeleteModel(
            name='Quises',
        ),
    ]
