# Generated by Django 2.2 on 2019-04-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0023_auto_20190414_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texto',
        ),
    ]
