# Generated by Django 2.2 on 2019-04-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0024_delete_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='aleatorio',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Pregunta_Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('narracion', models.BooleanField(default=True)),
                ('formato', models.CharField(choices=[('Imagen', 'Imagen'), ('Texto', 'Texto'), ('Sonido', 'Sonido'), ('Imagen+Sonido', 'Imagen+Sonido'), ('Video', 'Video')], default='Imagen', max_length=20)),
                ('multimediaCorrecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimediaCorrecto+', to='appQRMusical.Multimedia')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta_Quizz',
            fields=[
                ('pregunta_matching_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appQRMusical.Pregunta_Matching')),
                ('visualizacion', models.CharField(choices=[('Rejilla', 'Rejilla'), ('Unica', 'Unica')], default='Unica', max_length=20)),
                ('multimediaIncorrecto', models.ManyToManyField(related_name='_pregunta_quizz_multimediaIncorrecto_+', to='appQRMusical.Multimedia')),
            ],
            bases=('appQRMusical.pregunta_matching',),
        ),
        migrations.CreateModel(
            name='Actividad_Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Actividad')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQRMusical.Pregunta_Matching')),
            ],
            options={
                'unique_together': {('actividad', 'pregunta')},
            },
        ),
    ]
