# Generated by Django 2.2 on 2019-04-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0025_auto_20190415_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta_matching',
            name='multimediaCorrecto',
        ),
        migrations.RemoveField(
            model_name='pregunta_quizz',
            name='multimediaIncorrecto',
        ),
        migrations.RemoveField(
            model_name='pregunta_quizz',
            name='pregunta_matching_ptr',
        ),
        migrations.DeleteModel(
            name='Actividad_Pregunta',
        ),
        migrations.DeleteModel(
            name='Pregunta_Matching',
        ),
        migrations.DeleteModel(
            name='Pregunta_Quizz',
        ),
    ]
