# Generated by Django 2.2 on 2019-04-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0027_actividad_pregunta_pregunta_pregunta_matching_pregunta_quizz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='narracion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='narracion',
            field=models.BooleanField(default=True),
        ),
    ]
