# Generated by Django 2.2 on 2019-04-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0028_auto_20190416_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='file',
            new_name='audio',
        ),
    ]
