# Generated by Django 2.2 on 2019-04-19 16:33

import appQRMusical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0029_auto_20190419_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='video',
            field=models.FileField(blank=True, null=True),
        ),
    ]
