# Generated by Django 2.2 on 2019-04-19 18:07

import appQRMusical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0030_multimedia_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=appQRMusical.models.generarDirectorioSubida),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=appQRMusical.models.generarDirectorioSubida),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='formato',
            field=models.CharField(choices=[('Texto', 'Texto'), ('Imagen', 'Imagen'), ('Audio', 'Audio'), ('Video', 'Video')], default='Imagen', max_length=20),
        ),
        migrations.AlterField(
            model_name='pregunta_quizz',
            name='visualizacion',
            field=models.CharField(choices=[('Multiopcion', 'Multiopcion'), ('Unica', 'Unica')], default='Unica', max_length=20),
        ),
    ]
